### ISSUE TITLE
Add a video progress bar solution

### ISSUE THREAD

**Issue by wadawada** [GabrielDuarteM/youtube-autoclose-ads#103]
This is a feature request
Sometimes, I do want to watch an ads but I want to be able to skip to the later part to see what the ad is about. 
So I would like to have the progress bar enabled on ads like other youtube videos.
I could use extension like 
https://github.com/ettoolong/MaximizeVideo
but it completely changes the player and problems may occur when the ads is over and shift to the original video if I use this method

So I am wondering if you can create a solution that enables the progress bar on ads instead of yellow locked progress bar thanks

**Comment by GabeDuarteM** [comment]
Hi @wadawada 👋 👋 

Thank you for opening this feature request! This is something that should be possible, but I'd like to keep the scope of this extension small so that it doesn't become too bloated with features to support, and also to keep only simulating actions that the user can do on the original player so that it doesn't affect the YouTuber's ad revenue...

**Comment by wadawada** [comment]
Thanks for your reply. I think this feature can be developed in another extension if possible
To be honest, I use adblock a lot of times because I have not found an extension that fits my needs and this suggestion often gets ignored. However, I actually like, or not opposed to watch ads that are relevant that it brings many ideas.
I treat ads just like another youtube video so I skipped to the end if the ads is boring and repeat it if it is interesting. As I mentioned, there is another extension that kind of work for me that way except it is not designed for it so there are problems

I think ads should also earn its view count by its content, just like other videos. So I hope you can consider making an extension that allows ads to be played like this way, which is like any other video, The reason that I use adblock a lot of times is that I have no control over this ads videos, I have to play it linearly, which I don't always do with other videos.
I think a healthy way to support YouTubers is not to "tolerate" ads, quite the opposite, is to allow users to choose what ads to watch
