### ISSUE TITLE
Add support for Youtube Music.

### ISSUE THREAD

**Issue by ZeroDot1** [GabrielDuarteM/youtube-autoclose-ads#11]
https://music.youtube.com/

Example URL:
https://music.youtube.com/playlist?list=OLAK5uy_lnMsdR3VIi_PGlCJE7E7_5l2oEsGEAxiE

**Comment by GabeDuarteM** [comment]
Didn't even know that existed hahah

Unfortunately, I'm afraid I'll not be able to do that, as Youtube music doesn't seem to be available yet on my country (Brazil), so I can't even see how the service works...

**Comment by ZeroDot1** [comment]
OK, thanks, 
The extension works very well.
Keep up the good work.
